package com.laboratory.managementsystem;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

/**
 * Exposes optional native runtime capabilities to the web layer without
 * attempting to use services that are absent from a locally built APK.
 */
@CapacitorPlugin(name = "NativeRuntime")
public class NativeRuntimePlugin extends Plugin {
    @PluginMethod
    public void getConfiguration(PluginCall call) {
        // google_app_id is generated by the Google Services Gradle plugin only
        // when this application includes a valid google-services.json file.
        boolean firebasePushConfigured = getContext().getResources().getIdentifier(
            "google_app_id", "string", getContext().getPackageName()
        ) != 0;

        JSObject result = new JSObject();
        result.put("firebasePushConfigured", firebasePushConfigured);
        call.resolve(result);
    }
}
